# ===================================================================
# Phase 14 — R Analysis
# ===================================================================
#
# Reproducible R-based re-analysis of the demand, variability,
# inventory-scenario and forecasting evidence produced by Phases 11–13,
# independently verifying it across languages. The workflow consumes the
# compact analytical outputs generated by Phase 13 plus the stored Phase 12
# validation forecasts, rather than reloading the full integrated dataset
# unnecessarily.
#
# The project root is discovered by walking up from the working directory
# looking for `pyproject.toml` and `docs/`, and can be overridden — together
# with the input and output directories — through R_ANALYSIS_PROJECT_ROOT,
# R_ANALYSIS_INPUT_DIR and R_ANALYSIS_OUTPUT_DIR, which is how the automated
# tests run the complete workflow into a temporary directory.
#
# Every validation result is recorded in a machine-readable quality report
# (`r_analysis_quality_report.csv`) that gates the run. The workflow
# definition ends in `main()`, invoked only when this file is executed as a
# script; the R Markdown report sources the file and calls `main()`, so the
# report and the script verify the same evidence.
#
# Python remains the primary forecasting implementation. R is used here as
# an independent analytical, validation and reporting workflow.

REQUIRED_PACKAGES <- c(
  "tidyverse",
  "dplyr",
  "ggplot2",
  "readr",
  "tidymodels",
  "yardstick",
  "knitr",
  "rmarkdown"
)

INPUT_FILES <- c(
  demand = "inventory_demand_summary.csv",
  variability = "inventory_variability_summary.csv",
  scenarios = "inventory_scenarios.csv",
  forecast_scenarios = "inventory_forecast_scenarios.csv",
  forecast_errors = "inventory_forecast_error_summary.csv",
  densification = "inventory_densification_summary.csv",
  insights = "forecast_inventory_insights.csv",
  validation_results = "tuned_validation_results.csv",
  predictions = "model_evaluation_predictions.csv"
)

REQUIRED_COLUMNS <- list(
  demand = c(
    "store_id",
    "training_days",
    "total_quantity",
    "mean_daily_demand",
    "median_daily_demand",
    "min_daily_demand",
    "max_daily_demand",
    "coefficient_of_variation"
  ),
  variability = c(
    "store_id",
    "mean_daily_demand",
    "std_daily_demand",
    "variance_daily_demand",
    "p90_daily_demand",
    "p95_daily_demand",
    "p99_daily_demand",
    "coefficient_of_variation"
  ),
  scenarios = c(
    "store_id",
    "model",
    "configuration",
    "lead_time_days",
    "service_level",
    "z_value",
    "mean_daily_demand",
    "std_daily_demand",
    "expected_lead_time_demand",
    "safety_stock",
    "reorder_point"
  ),
  forecast_scenarios = c(
    "store_id",
    "model",
    "configuration",
    "lead_time_days",
    "service_level",
    "z_value",
    "model_daily_demand",
    "bias",
    "bias_adjusted_daily_demand",
    "residual_std",
    "rmse",
    "expected_lead_time_demand",
    "safety_stock",
    "reorder_point"
  ),
  forecast_errors = c(
    "store_id",
    "model",
    "configuration",
    "observations",
    "mean_predicted",
    "mean_actual",
    "bias",
    "residual_std",
    "rmse",
    "mape_percent"
  ),
  densification = c(
    "store_id",
    "observed_days",
    "densified_days",
    "synthetic_days",
    "first_date",
    "last_date"
  ),
  insights = c(
    "insight_type",
    "store_id",
    "metric",
    "value"
  ),
  validation_results = c(
    "store_id",
    "model",
    "configuration",
    "rmse",
    "mape_percent"
  ),
  predictions = c(
    "scope",
    "store_id",
    "actual",
    "predicted"
  )
)

# Planning scenario constants used for the headline comparison.
PLANNING_LEAD_TIME_DAYS <- 14
PLANNING_SERVICE_LEVEL <- 0.95

# Tolerances. Exact reproductions of stored float values use the tighter
# tolerance; metrics recomputed from rounded stored forecasts use the looser
# one because the predictions artifact carries only six decimal places.
RELATIVE_TOLERANCE <- 1e-6
METRIC_TOLERANCE <- 1e-4

SCENARIO_LEAD_TIMES <- c(7, 14, 28)
SCENARIO_SERVICE_LEVELS <- c(0.90, 0.95, 0.99)

INSIGHT_TYPES <- c(
  "highest_average_demand",
  "highest_relative_variability",
  "lowest_validation_rmse",
  "lowest_relative_validation_error",
  "systematic_bias",
  "inventory_scenario",
  "forecast_inventory_scenario"
)

# The metric each insight type must publish. A Phase 13 artifact that
# relabels a metric is a documentation defect the reconciliation must catch.
CANONICAL_METRICS <- c(
  highest_average_demand = "mean_daily_demand",
  highest_relative_variability = "coefficient_of_variation",
  lowest_validation_rmse = "validation_rmse",
  lowest_relative_validation_error = "validation_mape_percent",
  systematic_bias = "mean_forecast_bias",
  inventory_scenario = "reorder_point",
  forecast_inventory_scenario = "reorder_point"
)

PLOT_FILES <- c(
  "average_daily_demand_by_store.png",
  "demand_variability_by_store.png",
  "inventory_reorder_point_scenarios.png",
  "inventory_scenario_family_comparison.png"
)

# -------------------------------------------------------------------
# Quality-report helpers
# -------------------------------------------------------------------

empty_checks <- function() {
  data.frame(
    check = character(),
    passed = logical(),
    actual = character(),
    expected = character(),
    stringsAsFactors = FALSE
  )
}

new_check <- function(name, passed, actual, expected) {
  data.frame(
    check = name,
    passed = isTRUE(passed),
    actual = as.character(actual),
    expected = as.character(expected),
    stringsAsFactors = FALSE
  )
}

# Accumulator so every validation function records results in one place and
# the same evidence can both gate the run and be written to disk.
check_collector <- function() {
  collector <- new.env(parent = emptyenv())
  collector$rows <- list()

  collector$add <- function(name, passed, actual, expected) {
    collector$rows[[length(collector$rows) + 1L]] <- new_check(
      name,
      passed,
      actual,
      expected
    )
    invisible(NULL)
  }

  collector$frame <- function() {
    if (length(collector$rows) == 0L) {
      return(empty_checks())
    }
    do.call(rbind, collector$rows)
  }

  collector
}

combine_checks <- function(...) {
  frames <- Filter(
    function(frame) !is.null(frame) && nrow(frame) > 0L,
    list(...)
  )
  if (length(frames) == 0L) {
    return(empty_checks())
  }
  do.call(rbind, frames)
}

within_tolerance <- function(actual, expected, tolerance = RELATIVE_TOLERANCE) {
  if (length(actual) != length(expected)) {
    return(FALSE)
  }
  if (any(is.na(actual)) || any(is.na(expected))) {
    return(FALSE)
  }
  all(abs(actual - expected) <= tolerance * pmax(1, abs(expected)))
}

relative_difference <- function(actual, expected) {
  ifelse(
    is.na(actual) | is.na(expected),
    NA_real_,
    abs(actual - expected) / pmax(1, abs(expected))
  )
}

format_value <- function(value, digits = 6) {
  if (length(value) == 0L) {
    return(character())
  }
  formatC(as.numeric(value), format = "f", digits = digits)
}

describe_vector <- function(values) {
  paste(values, collapse = "|")
}

# -------------------------------------------------------------------
# Environment and paths
# -------------------------------------------------------------------

find_project_root <- function(start_dir = getwd()) {
  override <- Sys.getenv("R_ANALYSIS_PROJECT_ROOT", unset = "")

  if (nzchar(override)) {
    resolved <- normalizePath(override, winslash = "/", mustWork = TRUE)

    if (!file.exists(file.path(resolved, "pyproject.toml"))) {
      stop(
        paste(
          "R_ANALYSIS_PROJECT_ROOT does not contain pyproject.toml:",
          resolved
        ),
        call. = FALSE
      )
    }

    return(resolved)
  }

  current <- normalizePath(start_dir, winslash = "/", mustWork = TRUE)

  repeat {
    if (
      file.exists(file.path(current, "pyproject.toml")) &&
        dir.exists(file.path(current, "docs"))
    ) {
      return(current)
    }

    parent <- dirname(current)

    if (identical(parent, current)) {
      stop(
        paste0(
          "Could not locate the project root above ",
          normalizePath(start_dir, winslash = "/", mustWork = FALSE),
          ". Run the workflow from inside the repository or set ",
          "R_ANALYSIS_PROJECT_ROOT."
        ),
        call. = FALSE
      )
    }

    current <- parent
  }
}

resolve_paths <- function(project_root) {
  input_override <- Sys.getenv("R_ANALYSIS_INPUT_DIR", unset = "")

  input_dir <- if (nzchar(input_override)) {
    input_override
  } else {
    file.path(project_root, "data", "analysis")
  }

  output_override <- Sys.getenv("R_ANALYSIS_OUTPUT_DIR", unset = "")

  output_dir <- if (nzchar(output_override)) {
    output_override
  } else {
    file.path(input_dir, "r")
  }

  list(
    project_root = project_root,
    input_dir = normalizePath(input_dir, winslash = "/", mustWork = FALSE),
    output_dir = normalizePath(output_dir, winslash = "/", mustWork = FALSE),
    plot_dir = normalizePath(
      file.path(output_dir, "plots"),
      winslash = "/",
      mustWork = FALSE
    )
  )
}

check_required_packages <- function() {
  available <- vapply(
    REQUIRED_PACKAGES,
    requireNamespace,
    logical(1),
    quietly = TRUE
  )

  missing_packages <- REQUIRED_PACKAGES[!available]

  if (length(missing_packages) > 0L) {
    stop(
      paste(
        "Missing required R packages:",
        paste(missing_packages, collapse = ", ")
      ),
      call. = FALSE
    )
  }

  data.frame(
    package = REQUIRED_PACKAGES,
    version = vapply(
      REQUIRED_PACKAGES,
      function(package) as.character(utils::packageVersion(package)),
      character(1)
    ),
    stringsAsFactors = FALSE
  )
}

record_environment <- function(paths, packages) {
  pandoc_version <- tryCatch(
    {
      if (
        requireNamespace("rmarkdown", quietly = TRUE) &&
          isTRUE(rmarkdown::pandoc_available())
      ) {
        as.character(rmarkdown::pandoc_version())
      } else {
        "not available"
      }
    },
    error = function(condition) "not available"
  )

  environment <- rbind(
    data.frame(
      item = c(
        "r_version",
        "platform",
        "pandoc_version",
        "run_date",
        "input_dir"
      ),
      value = c(
        R.version.string,
        R.version$platform,
        pandoc_version,
        format(Sys.time(), tz = "UTC", usetz = TRUE),
        paths$input_dir
      ),
      stringsAsFactors = FALSE
    ),
    data.frame(
      item = paste0("package_", packages$package),
      value = packages$version,
      stringsAsFactors = FALSE
    )
  )

  readr::write_csv(
    environment,
    file.path(paths$output_dir, "r_environment.csv")
  )

  environment
}

# -------------------------------------------------------------------
# Input loading and validation
# -------------------------------------------------------------------

load_inputs <- function(input_dir) {
  files <- file.path(input_dir, INPUT_FILES)
  names(files) <- names(INPUT_FILES)

  present <- vapply(files, file.exists, logical(1))

  data <- list()

  for (key in names(INPUT_FILES)) {
    if (isTRUE(present[[key]])) {
      data[[key]] <- readr::read_csv(
        files[[key]],
        show_col_types = FALSE,
        progress = FALSE
      )
    }
  }

  list(files = files, present = present, data = data)
}

validate_inputs <- function(loaded, checks) {
  checks$add(
    "required_input_files_present",
    all(loaded$present),
    sum(loaded$present),
    length(loaded$present)
  )

  for (key in names(REQUIRED_COLUMNS)) {
    frame <- loaded$data[[key]]
    required <- REQUIRED_COLUMNS[[key]]

    if (is.null(frame)) {
      checks$add(
        paste0(key, "_columns_present"),
        FALSE,
        "file missing",
        describe_vector(required)
      )
      checks$add(
        paste0(key, "_not_empty"),
        FALSE,
        "file missing",
        "> 0"
      )
      next
    }

    missing_columns <- setdiff(required, names(frame))

    checks$add(
      paste0(key, "_columns_present"),
      length(missing_columns) == 0L,
      if (length(missing_columns) == 0L) {
        length(required)
      } else {
        paste(missing_columns, collapse = ",")
      },
      describe_vector(required)
    )

    if (length(missing_columns) == 0L) {
      missing_values <- sum(is.na(frame[required]))
      checks$add(
        paste0(key, "_no_missing_values"),
        missing_values == 0L,
        missing_values,
        0
      )
    }

    checks$add(
      paste0(key, "_not_empty"),
      nrow(frame) > 0L,
      nrow(frame),
      "> 0"
    )
  }

  # Downstream checks index required columns, so a missing file or a missing
  # column must stop the run here rather than fail later with an R error.
  incomplete_columns <- vapply(
    names(REQUIRED_COLUMNS),
    function(key) {
      frame <- loaded$data[[key]]
      is.null(frame) ||
        length(setdiff(REQUIRED_COLUMNS[[key]], names(frame))) > 0L
    },
    logical(1)
  )

  if (any(!loaded$present) || any(incomplete_columns)) {
    checks$add(
      "inputs_ready_for_analysis",
      FALSE,
      describe_vector(c(
        names(INPUT_FILES)[!loaded$present],
        names(incomplete_columns)[incomplete_columns]
      )),
      "all required inputs present with their required columns"
    )
    return(invisible(FALSE))
  }

  demand <- loaded$data$demand
  variability <- loaded$data$variability
  validation_results <- loaded$data$validation_results

  checks$add(
    "store_ids_unique_in_demand",
    dplyr::n_distinct(demand$store_id) == nrow(demand),
    dplyr::n_distinct(demand$store_id),
    nrow(demand)
  )

  checks$add(
    "store_ids_unique_in_variability",
    dplyr::n_distinct(variability$store_id) == nrow(variability),
    dplyr::n_distinct(variability$store_id),
    nrow(variability)
  )

  reference_stores <- sort(unique(demand$store_id))
  compared_stores <- c(
    variability = identical(
      sort(unique(variability$store_id)),
      reference_stores
    ),
    scenarios = identical(
      sort(unique(loaded$data$scenarios$store_id)),
      reference_stores
    ),
    forecast_scenarios = identical(
      sort(unique(loaded$data$forecast_scenarios$store_id)),
      reference_stores
    ),
    forecast_errors = identical(
      sort(unique(loaded$data$forecast_errors$store_id)),
      reference_stores
    ),
    densification = identical(
      sort(unique(loaded$data$densification$store_id)),
      reference_stores
    ),
    validation_results = identical(
      sort(unique(validation_results$store_id)),
      reference_stores
    )
  )

  checks$add(
    "store_sets_identical_across_inputs",
    all(compared_stores),
    describe_vector(names(compared_stores)[!compared_stores]),
    "same store set across demand, variability, scenarios, forecast scenarios, forecast errors, densification and validation results"
  )

  checks$add(
    "training_days_positive",
    all(demand$training_days > 0),
    min(demand$training_days),
    "> 0"
  )

  checks$add(
    "demand_values_non_negative",
    all(demand$mean_daily_demand >= 0) &&
      all(demand$median_daily_demand >= 0) &&
      all(demand$min_daily_demand >= 0) &&
      all(demand$max_daily_demand >= 0) &&
      all(demand$total_quantity >= 0),
    min(demand$min_daily_demand),
    ">= 0"
  )

  checks$add(
    "variability_values_non_negative",
    all(variability$mean_daily_demand >= 0) &&
      all(variability$std_daily_demand >= 0) &&
      all(variability$variance_daily_demand >= 0) &&
      all(variability$p90_daily_demand >= 0) &&
      all(variability$p95_daily_demand >= 0) &&
      all(variability$p99_daily_demand >= 0),
    min(variability$std_daily_demand),
    ">= 0"
  )

  checks$add(
    "percentiles_ordered",
    all(variability$p90_daily_demand <= variability$p95_daily_demand) &&
      all(variability$p95_daily_demand <= variability$p99_daily_demand),
    "p90 <= p95 <= p99",
    "p90 <= p95 <= p99"
  )

  mean_from_total <- demand$total_quantity / demand$training_days
  checks$add(
    "mean_matches_total_over_days",
    within_tolerance(
      demand$mean_daily_demand,
      mean_from_total,
      RELATIVE_TOLERANCE
    ),
    format_value(
      max(relative_difference(demand$mean_daily_demand, mean_from_total)),
      12
    ),
    paste("<=", RELATIVE_TOLERANCE)
  )

  variance_from_std <- variability$std_daily_demand^2
  checks$add(
    "variance_matches_standard_deviation",
    within_tolerance(
      variability$variance_daily_demand,
      variance_from_std,
      RELATIVE_TOLERANCE
    ),
    format_value(
      max(relative_difference(
        variability$variance_daily_demand,
        variance_from_std
      )),
      12
    ),
    paste("<=", RELATIVE_TOLERANCE)
  )

  coefficient_from_ratio <- variability$std_daily_demand /
    variability$mean_daily_demand

  joined_coefficient <- dplyr::inner_join(
    demand %>% dplyr::select(store_id, demand_cv = coefficient_of_variation),
    variability %>%
      dplyr::select(store_id, variability_cv = coefficient_of_variation),
    by = "store_id"
  )

  joined_coefficient$difference <- relative_difference(
    joined_coefficient$variability_cv,
    joined_coefficient$demand_cv
  )

  checks$add(
    "coefficient_of_variation_matches_ratio",
    within_tolerance(
      variability$coefficient_of_variation,
      coefficient_from_ratio,
      RELATIVE_TOLERANCE
    ) &&
      all(joined_coefficient$difference <= RELATIVE_TOLERANCE),
    format_value(
      max(c(
        max(relative_difference(
          variability$coefficient_of_variation,
          coefficient_from_ratio
        )),
        max(joined_coefficient$difference)
      )),
      12
    ),
    paste("<=", RELATIVE_TOLERANCE)
  )

  checks$add(
    "validation_results_non_negative",
    all(validation_results$rmse >= 0) &&
      all(validation_results$mape_percent >= 0),
    min(validation_results$rmse),
    ">= 0"
  )

  checks$add(
    "inputs_ready_for_analysis",
    all(checks$frame()$passed),
    sum(checks$frame()$passed),
    nrow(checks$frame())
  )

  invisible(all(checks$frame()$passed))
}

# -------------------------------------------------------------------
# Store-level demand analysis
# -------------------------------------------------------------------

build_store_analysis <- function(demand, variability) {
  demand %>%
    dplyr::select(
      store_id,
      training_days,
      total_quantity,
      mean_daily_demand,
      median_daily_demand,
      min_daily_demand,
      max_daily_demand,
      coefficient_of_variation
    ) %>%
    dplyr::left_join(
      variability %>%
        dplyr::select(
          store_id,
          std_daily_demand,
          variance_daily_demand,
          p90_daily_demand,
          p95_daily_demand,
          p99_daily_demand
        ),
      by = "store_id"
    ) %>%
    dplyr::arrange(dplyr::desc(mean_daily_demand))
}

# -------------------------------------------------------------------
# Scenario validation
# -------------------------------------------------------------------

validate_scenario_family <- function(
  frame,
  prefix,
  level_column,
  spread_column
) {
  checks <- empty_checks()

  store_count <- dplyr::n_distinct(frame$store_id)
  expected_rows <- store_count * length(SCENARIO_LEAD_TIMES) *
    length(SCENARIO_SERVICE_LEVELS)

  expected_lead_time_demand <- frame[[level_column]] * frame$lead_time_days
  expected_safety_stock <- frame$z_value *
    frame[[spread_column]] *
    sqrt(frame$lead_time_days)

  checks <- rbind(
    checks,
    new_check(
      paste0(prefix, "_scenario_coverage_complete"),
      nrow(frame) == expected_rows &&
        dplyr::n_distinct(
          frame$store_id,
          frame$lead_time_days,
          frame$service_level
        ) == expected_rows,
      nrow(frame),
      expected_rows
    ),
    new_check(
      paste0(prefix, "_lead_times_complete"),
      setequal(unique(frame$lead_time_days), SCENARIO_LEAD_TIMES),
      describe_vector(sort(unique(frame$lead_time_days))),
      describe_vector(SCENARIO_LEAD_TIMES)
    ),
    new_check(
      paste0(prefix, "_service_levels_complete"),
      setequal(unique(frame$service_level), SCENARIO_SERVICE_LEVELS),
      describe_vector(sort(unique(frame$service_level))),
      describe_vector(SCENARIO_SERVICE_LEVELS)
    ),
    new_check(
      paste0(prefix, "_service_level_z_values_match"),
      within_tolerance(
        frame$z_value,
        stats::qnorm(frame$service_level),
        1e-9
      ),
      format_value(
        max(abs(frame$z_value - stats::qnorm(frame$service_level))),
        12
      ),
      paste("<=", 1e-9)
    ),
    new_check(
      paste0(prefix, "_expected_lead_time_demand_formula_holds"),
      within_tolerance(
        frame$expected_lead_time_demand,
        expected_lead_time_demand,
        RELATIVE_TOLERANCE
      ),
      format_value(
        max(relative_difference(
          frame$expected_lead_time_demand,
          expected_lead_time_demand
        )),
        12
      ),
      paste("<=", RELATIVE_TOLERANCE)
    ),
    new_check(
      paste0(prefix, "_safety_stock_formula_holds"),
      within_tolerance(
        frame$safety_stock,
        expected_safety_stock,
        RELATIVE_TOLERANCE
      ),
      format_value(
        max(relative_difference(frame$safety_stock, expected_safety_stock)),
        12
      ),
      paste("<=", RELATIVE_TOLERANCE)
    ),
    new_check(
      paste0(prefix, "_reorder_point_formula_holds"),
      within_tolerance(
        frame$reorder_point,
        frame$expected_lead_time_demand + frame$safety_stock,
        RELATIVE_TOLERANCE
      ),
      format_value(
        max(relative_difference(
          frame$reorder_point,
          frame$expected_lead_time_demand + frame$safety_stock
        )),
        12
      ),
      paste("<=", RELATIVE_TOLERANCE)
    ),
    new_check(
      paste0(prefix, "_safety_stock_non_negative"),
      all(frame$safety_stock >= 0),
      min(frame$safety_stock),
      ">= 0"
    ),
    new_check(
      paste0(prefix, "_reorder_point_covers_lead_time_demand"),
      all(frame$reorder_point >= frame$expected_lead_time_demand),
      min(frame$reorder_point - frame$expected_lead_time_demand),
      ">= 0"
    )
  )

  safety_ordered <- frame %>%
    dplyr::group_by(store_id, lead_time_days) %>%
    dplyr::arrange(service_level, .by_group = TRUE) %>%
    dplyr::summarise(
      monotone = all(diff(safety_stock) > 0),
      .groups = "drop"
    )

  checks <- rbind(
    checks,
    new_check(
      paste0(prefix, "_safety_stock_monotonic_in_service_level"),
      all(safety_ordered$monotone),
      sum(safety_ordered$monotone),
      nrow(safety_ordered)
    )
  )

  lead_time_ordered <- frame %>%
    dplyr::group_by(store_id, service_level) %>%
    dplyr::arrange(lead_time_days, .by_group = TRUE) %>%
    dplyr::summarise(
      monotone = all(diff(expected_lead_time_demand) > 0),
      .groups = "drop"
    )

  checks <- rbind(
    checks,
    new_check(
      paste0(prefix, "_lead_time_demand_monotonic_in_lead_time"),
      all(lead_time_ordered$monotone),
      sum(lead_time_ordered$monotone),
      nrow(lead_time_ordered)
    )
  )

  checks
}

validate_scenario_families <- function(loaded, checks) {
  scenarios <- loaded$data$scenarios
  forecast_scenarios <- loaded$data$forecast_scenarios
  validation_results <- loaded$data$validation_results
  forecast_errors <- loaded$data$forecast_errors

  historical_checks <- validate_scenario_family(
    scenarios,
    "historical",
    "mean_daily_demand",
    "std_daily_demand"
  )

  forecast_checks <- validate_scenario_family(
    forecast_scenarios,
    "forecast",
    "bias_adjusted_daily_demand",
    "residual_std"
  )

  checks$add(
    "forecast_level_is_bias_corrected",
    within_tolerance(
      forecast_scenarios$model_daily_demand + forecast_scenarios$bias,
      forecast_scenarios$bias_adjusted_daily_demand,
      RELATIVE_TOLERANCE
    ),
    format_value(
      max(relative_difference(
        forecast_scenarios$model_daily_demand + forecast_scenarios$bias,
        forecast_scenarios$bias_adjusted_daily_demand
      )),
      12
    ),
    paste("<=", RELATIVE_TOLERANCE)
  )

  tuned <- validation_results %>%
    dplyr::select(
      store_id,
      tuned_model = model,
      tuned_configuration = configuration
    )

  scenario_configuration <- forecast_scenarios %>%
    dplyr::distinct(store_id, model, configuration) %>%
    dplyr::left_join(tuned, by = "store_id")

  configuration_matches <- scenario_configuration$model ==
    scenario_configuration$tuned_model &
    scenario_configuration$configuration ==
      scenario_configuration$tuned_configuration

  checks$add(
    "forecast_scenarios_use_tuned_configuration",
    all(configuration_matches),
    sum(configuration_matches),
    nrow(scenario_configuration)
  )

  error_join <- forecast_errors %>%
    dplyr::select(store_id, error_rmse = rmse, error_mape = mape_percent) %>%
    dplyr::inner_join(
      validation_results %>%
        dplyr::select(
          store_id,
          validation_rmse = rmse,
          validation_mape = mape_percent
        ),
      by = "store_id"
    )

  checks$add(
    "forecast_error_matches_validation",
    within_tolerance(
      error_join$error_rmse,
      error_join$validation_rmse,
      METRIC_TOLERANCE
    ) &&
      within_tolerance(
        error_join$error_mape,
        error_join$validation_mape,
        METRIC_TOLERANCE
      ),
    format_value(
      max(relative_difference(
        error_join$error_rmse,
        error_join$validation_rmse
      )),
      12
    ),
    paste("<=", METRIC_TOLERANCE)
  )

  rbind(historical_checks, forecast_checks)
}

# -------------------------------------------------------------------
# Scenario summaries
# -------------------------------------------------------------------

summarise_scenarios <- function(frame) {
  frame %>%
    dplyr::group_by(lead_time_days, service_level) %>%
    dplyr::summarise(
      stores = dplyr::n_distinct(store_id),
      average_reorder_point = mean(reorder_point),
      maximum_reorder_point = max(reorder_point),
      average_safety_stock = mean(safety_stock),
      .groups = "drop"
    ) %>%
    dplyr::arrange(lead_time_days, service_level)
}

baseline_scenario <- function(frame, columns) {
  frame %>%
    dplyr::filter(
      lead_time_days == PLANNING_LEAD_TIME_DAYS,
      service_level == PLANNING_SERVICE_LEVEL
    ) %>%
    dplyr::select(dplyr::all_of(columns)) %>%
    dplyr::arrange(store_id)
}

# -------------------------------------------------------------------
# Phase 13 reconciliation
# -------------------------------------------------------------------

reconcile_phase13 <- function(loaded, store_analysis, checks) {
  insights <- loaded$data$insights
  validation_results <- loaded$data$validation_results
  scenarios <- loaded$data$scenarios
  forecast_scenarios <- loaded$data$forecast_scenarios

  highest_demand <- store_analysis %>%
    dplyr::slice_max(order_by = mean_daily_demand, n = 1, with_ties = FALSE)

  highest_variability <- store_analysis %>%
    dplyr::slice_max(
      order_by = coefficient_of_variation,
      n = 1,
      with_ties = FALSE
    )

  lowest_rmse <- validation_results %>%
    dplyr::slice_min(order_by = rmse, n = 1, with_ties = FALSE)

  lowest_mape <- validation_results %>%
    dplyr::slice_min(order_by = mape_percent, n = 1, with_ties = FALSE)

  largest_bias <- loaded$data$forecast_errors %>%
    dplyr::slice_max(order_by = bias, n = 1, with_ties = FALSE)

  historical_baseline <- baseline_scenario(
    scenarios,
    c("store_id", "reorder_point")
  ) %>%
    dplyr::rename(historical_reorder_point = reorder_point)

  forecast_baseline <- baseline_scenario(
    forecast_scenarios,
    c("store_id", "reorder_point")
  ) %>%
    dplyr::rename(forecast_reorder_point = reorder_point)

  expected <- rbind(
    data.frame(
      insight_type = "highest_average_demand",
      store_id = highest_demand$store_id,
      metric = "mean_daily_demand",
      r_value = highest_demand$mean_daily_demand,
      stringsAsFactors = FALSE
    ),
    data.frame(
      insight_type = "highest_relative_variability",
      store_id = highest_variability$store_id,
      metric = "coefficient_of_variation",
      r_value = highest_variability$coefficient_of_variation,
      stringsAsFactors = FALSE
    ),
    data.frame(
      insight_type = "lowest_validation_rmse",
      store_id = lowest_rmse$store_id,
      metric = "validation_rmse",
      r_value = lowest_rmse$rmse,
      stringsAsFactors = FALSE
    ),
    data.frame(
      insight_type = "lowest_relative_validation_error",
      store_id = lowest_mape$store_id,
      metric = "validation_mape_percent",
      r_value = lowest_mape$mape_percent,
      stringsAsFactors = FALSE
    ),
    data.frame(
      insight_type = "systematic_bias",
      store_id = largest_bias$store_id,
      metric = "mean_forecast_bias",
      r_value = largest_bias$bias,
      stringsAsFactors = FALSE
    ),
    historical_baseline %>%
      dplyr::transmute(
        insight_type = "inventory_scenario",
        store_id = store_id,
        metric = "reorder_point",
        r_value = historical_reorder_point
      ),
    forecast_baseline %>%
      dplyr::transmute(
        insight_type = "forecast_inventory_scenario",
        store_id = store_id,
        metric = "reorder_point",
        r_value = forecast_reorder_point
      )
  )

  published <- insights %>%
    dplyr::select(
      insight_type,
      store_id,
      metric,
      phase13_value = value
    )

  reconciliation <- dplyr::inner_join(
    published,
    expected,
    by = c("insight_type", "store_id")
  )

  reconciliation$metric_matches <- reconciliation$metric.x ==
    reconciliation$metric.y
  reconciliation$relative_difference <- relative_difference(
    reconciliation$r_value,
    reconciliation$phase13_value
  )
  reconciliation$match <- reconciliation$metric_matches &
    reconciliation$relative_difference <= RELATIVE_TOLERANCE

  reconciliation <- reconciliation %>%
    dplyr::transmute(
      insight_type,
      store_id,
      metric = metric.x,
      phase13_value,
      r_value,
      relative_difference,
      match
    ) %>%
    dplyr::arrange(insight_type, store_id)

  checks$add(
    "phase13_insight_types_complete",
    setequal(unique(insights$insight_type), INSIGHT_TYPES),
    describe_vector(sort(unique(insights$insight_type))),
    describe_vector(INSIGHT_TYPES)
  )

  checks$add(
    "phase13_insight_rows_reconciled",
    nrow(reconciliation) == nrow(insights),
    nrow(reconciliation),
    nrow(insights)
  )

  for (insight_type in INSIGHT_TYPES) {
    rows <- reconciliation[reconciliation$insight_type == insight_type, ]

    checks$add(
      paste0("phase13_", insight_type, "_reconciles"),
      nrow(rows) > 0L && all(rows$match),
      sum(rows$match),
      nrow(rows)
    )
  }

  canonical <- data.frame(
    insight_type = names(CANONICAL_METRICS),
    canonical_metric = unname(CANONICAL_METRICS),
    stringsAsFactors = FALSE
  )

  labelled <- published %>%
    dplyr::left_join(canonical, by = "insight_type")

  checks$add(
    "phase13_metric_names_reconcile",
    all(!is.na(labelled$canonical_metric)) &&
      all(labelled$metric == labelled$canonical_metric),
    sum(labelled$metric == labelled$canonical_metric),
    nrow(labelled)
  )

  store_analysis_consistency <- reconciliation[
    reconciliation$insight_type == "highest_average_demand",
  ]

  # A published insight that names a store R did not select cannot be joined,
  # so the row count is reported instead of assuming a match exists.
  matched_store <- if (nrow(store_analysis_consistency) == 1L) {
    as.character(store_analysis_consistency$store_id)
  } else {
    paste0(nrow(store_analysis_consistency), " reconciled row(s)")
  }

  checks$add(
    "phase13_highest_demand_store_reconciles",
    nrow(store_analysis_consistency) == 1L &&
      store_analysis_consistency$store_id == highest_demand$store_id &&
      store_analysis_consistency$match,
    matched_store,
    as.character(highest_demand$store_id)
  )

  list(
    reconciliation = reconciliation,
    highest_demand = highest_demand,
    highest_variability = highest_variability
  )
}

# -------------------------------------------------------------------
# Phase 12 metric recomputation (tidymodels/yardstick)
# -------------------------------------------------------------------

recompute_validation_metrics <- function(loaded, checks) {
  predictions <- loaded$data$predictions
  forecast_errors <- loaded$data$forecast_errors
  validation_results <- loaded$data$validation_results

  checks$add(
    "prediction_scopes_recognised",
    all(unique(predictions$scope) %in% c("cv_fold", "validation")),
    describe_vector(sort(unique(predictions$scope))),
    "cv_fold|validation"
  )

  checks$add(
    "test_period_excluded",
    !any(predictions$scope == "test"),
    sum(predictions$scope == "test"),
    0
  )

  validation_predictions <- predictions %>%
    dplyr::filter(scope == "validation")

  checks$add(
    "validation_predictions_present",
    nrow(validation_predictions) > 0L,
    nrow(validation_predictions),
    "> 0"
  )

  metrics <- validation_predictions %>%
    dplyr::group_by(store_id) %>%
    dplyr::summarise(
      observations = dplyr::n(),
      rmse = yardstick::rmse_vec(actual, predicted),
      mae = yardstick::mae_vec(actual, predicted),
      # yardstick reports MAPE as a percentage, matching the Phase 12 field.
      mape_percent = yardstick::mape_vec(actual, predicted),
      .groups = "drop"
    ) %>%
    dplyr::arrange(store_id)

  reported <- validation_results %>%
    dplyr::select(
      store_id,
      reported_rmse = rmse,
      reported_mape_percent = mape_percent
    ) %>%
    dplyr::inner_join(
      forecast_errors %>%
        dplyr::select(store_id, error_observations = observations),
      by = "store_id"
    )

  reconciliation <- metrics %>%
    dplyr::left_join(reported, by = "store_id")

  reconciliation$rmse_relative_difference <- relative_difference(
    reconciliation$rmse,
    reconciliation$reported_rmse
  )
  reconciliation$mape_relative_difference <- relative_difference(
    reconciliation$mape_percent,
    reconciliation$reported_mape_percent
  )

  checks$add(
    "recomputed_metrics_cover_all_stores",
    nrow(metrics) == nrow(validation_results) &&
      setequal(metrics$store_id, validation_results$store_id),
    nrow(metrics),
    nrow(validation_results)
  )

  checks$add(
    "recomputed_observations_reconcile",
    all(reconciliation$observations == reconciliation$error_observations),
    describe_vector(reconciliation$observations),
    describe_vector(reconciliation$error_observations)
  )

  checks$add(
    "recomputed_rmse_reconciles_with_phase12",
    within_tolerance(
      reconciliation$rmse,
      reconciliation$reported_rmse,
      METRIC_TOLERANCE
    ),
    format_value(max(reconciliation$rmse_relative_difference), 12),
    paste("<=", METRIC_TOLERANCE)
  )

  checks$add(
    "recomputed_mape_reconciles_with_phase12",
    within_tolerance(
      reconciliation$mape_percent,
      reconciliation$reported_mape_percent,
      METRIC_TOLERANCE
    ),
    format_value(max(reconciliation$mape_relative_difference), 12),
    paste("<=", METRIC_TOLERANCE)
  )

  reconciliation
}

# -------------------------------------------------------------------
# Densification reconciliation
# -------------------------------------------------------------------

reconcile_densification <- function(loaded, checks) {
  densification <- loaded$data$densification
  demand <- loaded$data$demand

  joined <- demand %>%
    dplyr::select(store_id, training_days) %>%
    dplyr::inner_join(
      densification %>%
        dplyr::select(
          store_id,
          observed_days,
          densified_days,
          synthetic_days
        ),
      by = "store_id"
    )

  checks$add(
    "densification_matches_training_days",
    all(joined$training_days == joined$densified_days),
    describe_vector(joined$densified_days),
    describe_vector(joined$training_days)
  )

  checks$add(
    "densification_totals_reconcile",
    sum(densification$densified_days) == sum(demand$training_days),
    sum(densification$densified_days),
    sum(demand$training_days)
  )

  checks$add(
    "synthetic_days_measured_consistently",
    all(
      densification$densified_days - densification$observed_days ==
        densification$synthetic_days
    ),
    sum(densification$synthetic_days),
    "densified - observed == synthetic"
  )

  checks$add(
    "zero_filled_days_are_minimal",
    sum(densification$synthetic_days) == 1L,
    sum(densification$synthetic_days),
    1
  )

  joined
}

# -------------------------------------------------------------------
# Plots
# -------------------------------------------------------------------

build_plots <- function(
  store_analysis,
  scenarios,
  forecast_scenarios,
  plot_dir
) {
  written <- character()

  demand_plot <- ggplot2::ggplot(
    store_analysis,
    ggplot2::aes(x = factor(store_id), y = mean_daily_demand)
  ) +
    ggplot2::geom_col() +
    ggplot2::labs(
      title = "Average Daily Demand by Store",
      subtitle = "Densified training store-day series (Phases 11-13 basis)",
      x = "Store",
      y = "Mean Daily Demand"
    ) +
    ggplot2::theme_minimal()

  suppressMessages(
    ggplot2::ggsave(
      filename = file.path(plot_dir, "average_daily_demand_by_store.png"),
      plot = demand_plot,
      width = 8,
      height = 5,
      dpi = 150
    )
  )
  written <- c(written, "average_daily_demand_by_store.png")

  variability_plot <- ggplot2::ggplot(
    store_analysis,
    ggplot2::aes(x = factor(store_id), y = coefficient_of_variation)
  ) +
    ggplot2::geom_col() +
    ggplot2::labs(
      title = "Relative Demand Variability by Store",
      subtitle = "Coefficient of variation (standard deviation / mean)",
      x = "Store",
      y = "Coefficient of Variation"
    ) +
    ggplot2::theme_minimal()

  suppressMessages(
    ggplot2::ggsave(
      filename = file.path(plot_dir, "demand_variability_by_store.png"),
      plot = variability_plot,
      width = 8,
      height = 5,
      dpi = 150
    )
  )
  written <- c(written, "demand_variability_by_store.png")

  scenario_plot <- scenarios %>%
    ggplot2::ggplot(
      ggplot2::aes(
        x = lead_time_days,
        y = reorder_point,
        group = service_level,
        linetype = factor(service_level)
      )
    ) +
    ggplot2::geom_line() +
    ggplot2::geom_point() +
    ggplot2::facet_wrap(~ store_id) +
    ggplot2::labs(
      title = "Historical Scenario Reorder Points by Lead Time and Service Level",
      x = "Lead Time (Days)",
      y = "Reorder Point",
      linetype = "Service Level"
    ) +
    ggplot2::theme_minimal()

  suppressMessages(
    ggplot2::ggsave(
      filename = file.path(plot_dir, "inventory_reorder_point_scenarios.png"),
      plot = scenario_plot,
      width = 10,
      height = 7,
      dpi = 150
    )
  )
  written <- c(written, "inventory_reorder_point_scenarios.png")

  comparison_plot <- dplyr::bind_rows(
    scenarios %>%
      dplyr::mutate(family = "historical variability"),
    forecast_scenarios %>%
      dplyr::mutate(family = "forecast residual error")
  ) %>%
    ggplot2::ggplot(
      ggplot2::aes(
        x = lead_time_days,
        y = reorder_point,
        colour = family,
        linetype = factor(service_level)
      )
    ) +
    ggplot2::geom_line() +
    ggplot2::geom_point() +
    ggplot2::facet_wrap(~ store_id) +
    ggplot2::labs(
      title = "Reorder-Point Scenarios: Historical Variability vs Forecast Error",
      x = "Lead Time (Days)",
      y = "Reorder Point",
      colour = "Uncertainty input",
      linetype = "Service Level"
    ) +
    ggplot2::theme_minimal()

  suppressMessages(
    ggplot2::ggsave(
      filename = file.path(plot_dir, "inventory_scenario_family_comparison.png"),
      plot = comparison_plot,
      width = 11,
      height = 7,
      dpi = 150
    )
  )
  written <- c(written, "inventory_scenario_family_comparison.png")

  written
}

verify_plots <- function(plot_dir, written, checks) {
  paths <- file.path(plot_dir, written)
  sizes <- file.info(paths)$size

  checks$add(
    "plots_written",
    all(file.exists(paths)),
    sum(file.exists(paths)),
    length(paths)
  )

  checks$add(
    "plots_non_empty",
    all(!is.na(sizes) & sizes > 0),
    format_value(min(sizes, na.rm = TRUE), 0),
    "> 0 bytes"
  )

  checks$add(
    "plots_regenerated_from_analytical_data",
    identical(sort(written), sort(PLOT_FILES)),
    describe_vector(sort(written)),
    describe_vector(sort(PLOT_FILES))
  )

  invisible(paths)
}

# -------------------------------------------------------------------
# Findings
# -------------------------------------------------------------------

write_findings <- function(paths, results) {
  reconciliation <- results$reconciliation
  metrics <- results$metrics

  historical_baseline <- results$historical_baseline
  forecast_baseline <- results$forecast_baseline

  store_notes <- reconciliation %>%
    dplyr::filter(insight_type == "highest_average_demand")
  variability_notes <- reconciliation %>%
    dplyr::filter(insight_type == "highest_relative_variability")

  findings <- c(
    "Phase 14 - R Analysis Findings",
    "",
    paste("Generated:", format(Sys.time(), tz = "UTC", usetz = TRUE)),
    paste("R:", R.version.string),
    paste("Input directory:", paths$input_dir),
    "",
    "Evidence basis:",
    paste0(
      "- Training store-days reconciled with Phase 13: ",
      sum(results$densification$densified_days),
      " (observed ",
      sum(results$densification$observed_days),
      ", zero-filled ",
      sum(results$densification$synthetic_days),
      ")"
    ),
    paste(
      "- Inventory scenarios analysed per family:",
      nrow(results$scenarios),
      "historical and",
      nrow(results$forecast_scenarios),
      "forecast-error"
    ),
    paste(
      "- Phase 12 validation forecasts independently recomputed in R:",
      sum(metrics$observations)
    ),
    "",
    "Historical demand:",
    paste(
      "- Highest average daily demand store:",
      results$highest_demand$store_id
    ),
    paste(
      "- Mean daily demand:",
      format_value(results$highest_demand$mean_daily_demand, 3)
    ),
    paste(
      "- Highest relative variability store:",
      results$highest_variability$store_id
    ),
    paste(
      "- Coefficient of variation:",
      format_value(results$highest_variability$coefficient_of_variation, 6)
    ),
    "",
    "Cross-language verification:",
    paste(
      "- Recomputed RMSE vs Phase 12 maximum relative difference:",
      format_value(max(metrics$rmse_relative_difference), 10)
    ),
    paste(
      "- Recomputed MAPE vs Phase 12 maximum relative difference:",
      format_value(max(metrics$mape_relative_difference), 10)
    ),
    paste(
      "- Phase 13 insight rows reconciled:",
      sum(reconciliation$match),
      "of",
      nrow(reconciliation)
    ),
    "",
    "Planning scenario (14-day lead time, 95% service level):",
    paste(
      "- Historical-variability reorder points:",
      paste(
        paste0(
          historical_baseline$store_id,
          " = ",
          format_value(historical_baseline$reorder_point, 0)
        ),
        collapse = "; "
      )
    ),
    paste(
      "- Forecast-error reorder points:",
      paste(
        paste0(
          forecast_baseline$store_id,
          " = ",
          format_value(forecast_baseline$reorder_point, 0)
        ),
        collapse = "; "
      )
    ),
    "",
    "Quality:",
    paste(
      "- Quality checks passed:",
      sum(results$quality$passed),
      "of",
      nrow(results$quality)
    ),
    paste(
      "- Store-level consistency with Phase 13:",
      ifelse(all(reconciliation$match), "verified", "NOT verified")
    ),
    "",
    "Interpretation:",
    paste(
      "- R independently reproduces the Phase 13 store-level findings: store",
      store_notes$store_id,
      "leads on average demand and store",
      variability_notes$store_id,
      "on relative variability."
    ),
    paste(
      "- Recomputed validation metrics agree with the Phase 12 artifacts, so",
      "the forecast evidence is verified in a second language."
    ),
    paste(
      "- Mean absolute error is reported here as additional evidence; Phase 12",
      "did not publish it, so it is an R-derived statistic rather than a",
      "reconciliation."
    ),
    "",
    "Limitations:",
    "- Inventory values are planning scenarios, not operational requirements.",
    "- The dataset provides no supplier lead times, service-level requirements,",
    "  holding costs, ordering costs, stockout costs, current stock, purchase",
    "  orders or warehouse constraints.",
    "- Store 4 has 60 training days and one cross-validation fold, so its",
    "  variability and forecast-error estimates rest on fewer observations",
    "  than the other stores.",
    "- R does not replace or retrain the validated Python forecasting models.",
    "",
    "Reproducibility:",
    "- Regenerate with: Rscript r/r_analysis.R",
    "- Render the report with:",
    "  Rscript -e \"rmarkdown::render('r/r_analysis_report.Rmd')\""
  )

  writeLines(findings, file.path(paths$output_dir, "r_analysis_findings.txt"))
  findings
}

# -------------------------------------------------------------------
# Quality report
# -------------------------------------------------------------------

write_quality_report <- function(report, paths) {
  readr::write_csv(
    report,
    file.path(paths$output_dir, "r_analysis_quality_report.csv")
  )
  report
}

gate_quality_report <- function(report) {
  failed <- report[!report$passed, , drop = FALSE]

  if (nrow(failed) > 0L) {
    message(
      "Failed quality checks: ",
      paste(failed$check, collapse = ", ")
    )
    stop(
      paste0(
        "Phase 14 R analysis failed validation: ",
        nrow(failed),
        " of ",
        nrow(report),
        " checks failed. See r_analysis_quality_report.csv."
      ),
      call. = FALSE
    )
  }

  invisible(TRUE)
}

# -------------------------------------------------------------------
# Main workflow
# -------------------------------------------------------------------

main <- function() {
  paths <- resolve_paths(find_project_root())

  dir.create(paths$output_dir, recursive = TRUE, showWarnings = FALSE)
  dir.create(paths$plot_dir, recursive = TRUE, showWarnings = FALSE)

  packages <- check_required_packages()

  suppressPackageStartupMessages({
    library(tidyverse)
    library(yardstick)
  })

  checks <- check_collector()

  loaded <- load_inputs(paths$input_dir)
  inputs_ready <- validate_inputs(loaded, checks)

  if (!isTRUE(inputs_ready)) {
    report <- write_quality_report(checks$frame(), paths)
    record_environment(paths, packages)
    gate_quality_report(report)
  }

  scenario_checks <- validate_scenario_families(loaded, checks)

  store_analysis <- build_store_analysis(
    loaded$data$demand,
    loaded$data$variability
  )

  scenarios <- loaded$data$scenarios
  forecast_scenarios <- loaded$data$forecast_scenarios

  scenario_summary <- summarise_scenarios(scenarios)
  forecast_scenario_summary <- summarise_scenarios(forecast_scenarios)

  historical_baseline <- baseline_scenario(
    scenarios,
    c(
      "store_id",
      "model",
      "configuration",
      "mean_daily_demand",
      "std_daily_demand",
      "expected_lead_time_demand",
      "safety_stock",
      "reorder_point"
    )
  )

  forecast_baseline <- baseline_scenario(
    forecast_scenarios,
    c(
      "store_id",
      "model",
      "configuration",
      "model_daily_demand",
      "bias",
      "bias_adjusted_daily_demand",
      "residual_std",
      "rmse",
      "expected_lead_time_demand",
      "safety_stock",
      "reorder_point"
    )
  )

  reconciliation_results <- reconcile_phase13(loaded, store_analysis, checks)

  metrics <- recompute_validation_metrics(loaded, checks)

  densification <- reconcile_densification(loaded, checks)

  written_plots <- build_plots(
    store_analysis,
    scenarios,
    forecast_scenarios,
    paths$plot_dir
  )

  verify_plots(paths$plot_dir, written_plots, checks)

  quality <- combine_checks(
    checks$frame(),
    scenario_checks,
    new_check(
      "historical_and_forecast_scenarios_share_store_set",
      setequal(scenarios$store_id, forecast_scenarios$store_id),
      describe_vector(sort(unique(forecast_scenarios$store_id))),
      describe_vector(sort(unique(scenarios$store_id)))
    )
  )

  readr::write_csv(
    store_analysis,
    file.path(paths$output_dir, "r_store_analysis.csv")
  )

  readr::write_csv(
    scenario_summary,
    file.path(paths$output_dir, "r_inventory_scenario_summary.csv")
  )

  readr::write_csv(
    forecast_scenario_summary,
    file.path(paths$output_dir, "r_forecast_inventory_scenario_summary.csv")
  )

  readr::write_csv(
    historical_baseline,
    file.path(paths$output_dir, "r_baseline_inventory_scenario.csv")
  )

  readr::write_csv(
    forecast_baseline,
    file.path(paths$output_dir, "r_baseline_forecast_inventory_scenario.csv")
  )

  consistency <- reconciliation_results$reconciliation %>%
    dplyr::filter(
      insight_type %in% c(
        "highest_average_demand",
        "highest_relative_variability"
      )
    ) %>%
    dplyr::transmute(
      check = insight_type,
      phase_13_store = store_id,
      r_store = store_id,
      match
    )

  readr::write_csv(
    consistency,
    file.path(paths$output_dir, "r_phase13_consistency.csv")
  )

  readr::write_csv(
    reconciliation_results$reconciliation,
    file.path(paths$output_dir, "r_phase13_reconciliation.csv")
  )

  readr::write_csv(
    metrics,
    file.path(paths$output_dir, "r_metric_reconciliation.csv")
  )

  environment <- record_environment(paths, packages)

  write_quality_report(quality, paths)

  gate_quality_report(quality)

  results <- list(
    paths = paths,
    packages = packages,
    environment = environment,
    inputs = loaded$data,
    store_analysis = store_analysis,
    scenarios = scenarios,
    forecast_scenarios = forecast_scenarios,
    scenario_summary = scenario_summary,
    forecast_scenario_summary = forecast_scenario_summary,
    historical_baseline = historical_baseline,
    forecast_baseline = forecast_baseline,
    reconciliation = reconciliation_results$reconciliation,
    highest_demand = reconciliation_results$highest_demand,
    highest_variability = reconciliation_results$highest_variability,
    metrics = metrics,
    densification = densification,
    quality = quality,
    plots = written_plots
  )

  results$findings <- write_findings(paths, results)

  cat("Phase 14 R analysis completed successfully.\n")
  cat("Quality checks passed:", sum(quality$passed), "of", nrow(quality), "\n")
  cat(
    "R output directory:",
    normalizePath(paths$output_dir, winslash = "/"),
    "\n"
  )
  cat(
    "Render the report with (from the repository root):",
    paste0(
      "Rscript -e \"rmarkdown::render('r/r_analysis_report.Rmd', ",
      "output_dir = file.path(getwd(), 'data', 'analysis', 'r'))\"\n"
    )
  )

  invisible(results)
}

# Invoked only when this file is executed as a script. When the R Markdown
# report sources this file, it calls main() itself so the report and the
# script verify the same evidence.
if (sys.nframe() == 0L) {
  main()
}
